<?php

declare(strict_types=1);

namespace Lattice\Compiler\Manifest;

use Lattice\Compiler\Graph\ModuleGraph;

final class ManifestCompiler
{
    /**
     * Compile a module graph into a cached PHP manifest file.
     */
    public function compile(ModuleGraph $graph, string $outputPath): void
    {
        $modules = [];

        foreach ($graph->getModules() as $name => $node) {
            $modules[$name] = $node->toArray();
        }

        $data = [
            'modules' => $modules,
            'topological_order' => $graph->getTopologicalOrder(),
            'compiled_at' => time(),
        ];

        $dir = dirname($outputPath);

        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        $content = "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by Lattice ManifestCompiler. Do not edit.\nreturn " . var_export($data, true) . ";\n";

        file_put_contents($outputPath, $content);
    }
}
