<?php

declare(strict_types=1);

namespace Lattice\Compiler\Manifest;

use Lattice\Compiler\Discovery\ControllerMetadata;

final class RouteManifestCompiler
{
    /**
     * Compile controller/route metadata into a cached PHP manifest file.
     *
     * @param array<ControllerMetadata> $controllers
     */
    public function compile(array $controllers, string $outputPath): void
    {
        $data = [];

        foreach ($controllers as $controller) {
            $data[] = [
                'className' => $controller->className,
                'prefix' => $controller->prefix,
            ];
        }

        $dir = dirname($outputPath);

        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        $content = "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by Lattice RouteManifestCompiler. Do not edit.\nreturn " . var_export($data, true) . ";\n";

        file_put_contents($outputPath, $content);
    }
}
