<?php

declare(strict_types=1);

namespace Lattice\Catalyst\Guidelines;

final class GuidelineGenerator
{
    private readonly GuidelineRegistry $registry;

    /** @var array<string, string> Detected packages: name => version */
    private array $detectedPackages = [];

    public function __construct(?GuidelineRegistry $registry = null)
    {
        $this->registry = $registry ?? new GuidelineRegistry();
    }

    public function getRegistry(): GuidelineRegistry
    {
        return $this->registry;
    }

    /**
     * Detect installed lattice packages from composer.lock.
     *
     * @return array<string, string> package name => version
     */
    public function detectPackages(string $basePath): array
    {
        $this->detectedPackages = [];
        $lockFile = $basePath . '/composer.lock';

        if (!file_exists($lockFile)) {
            return $this->detectFromComposerJson($basePath);
        }

        $lockContent = file_get_contents($lockFile);

        if ($lockContent === false) {
            return [];
        }

        $lock = json_decode($lockContent, true);

        if (!is_array($lock)) {
            return [];
        }

        $packages = array_merge(
            $lock['packages'] ?? [],
            $lock['packages-dev'] ?? [],
        );

        foreach ($packages as $package) {
            if (!is_array($package)) {
                continue;
            }

            $name = $package['name'] ?? '';

            if (str_starts_with($name, 'lattice/')) {
                $shortName = substr($name, 8); // Remove 'lattice/' prefix
                $this->detectedPackages[$shortName] = $package['version'] ?? 'unknown';
            }
        }

        return $this->detectedPackages;
    }

    /**
     * Fallback: detect from composer.json require/require-dev.
     *
     * @return array<string, string>
     */
    private function detectFromComposerJson(string $basePath): array
    {
        $composerFile = $basePath . '/composer.json';

        if (!file_exists($composerFile)) {
            return [];
        }

        $content = file_get_contents($composerFile);

        if ($content === false) {
            return [];
        }

        $composer = json_decode($content, true);

        if (!is_array($composer)) {
            return [];
        }

        $allDeps = array_merge(
            $composer['require'] ?? [],
            $composer['require-dev'] ?? [],
        );

        foreach ($allDeps as $name => $constraint) {
            if (str_starts_with($name, 'lattice/')) {
                $shortName = substr($name, 8);
                $this->detectedPackages[$shortName] = (string) $constraint;
            }
        }

        return $this->detectedPackages;
    }

    /**
     * Load built-in guidelines and register them with the registry.
     */
    public function loadBuiltinGuidelines(): void
    {
        $builtinDir = dirname(__DIR__, 2) . '/resources/guidelines';
        $this->registry->loadFromDirectory($builtinDir);
    }

    /**
     * Load custom project-level guidelines (override bundled ones).
     */
    public function loadCustomGuidelines(string $basePath): void
    {
        $customDir = $basePath . '/.ai/guidelines';
        $this->registry->loadFromDirectory($customDir);
    }

    /**
     * Generate the CLAUDE.md content from all loaded guidelines.
     *
     * @param array<string, string> $packages Package name => version map
     */
    public function generateClaudeMd(array $packages, string $basePath = ''): string
    {
        $lines = [];
        $lines[] = '# CLAUDE.md -- LatticePHP Project Guidelines';
        $lines[] = '';
        $lines[] = '> Auto-generated by `php lattice catalyst:install`. Do not edit manually.';
        $lines[] = '';

        // Project context
        $lines[] = '## Project Context';
        $lines[] = '';
        $lines[] = '- **PHP Version:** ' . PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;
        $lines[] = '- **Framework:** LatticePHP';
        $lines[] = '- **Installed Packages:** ' . count($packages);
        $lines[] = '';

        if ($packages !== []) {
            $lines[] = '### Installed Packages';
            $lines[] = '';

            foreach ($packages as $name => $version) {
                $lines[] = '- `lattice/' . $name . '` ' . $version;
            }

            $lines[] = '';
        }

        // Include guidelines for detected packages
        $guidelineCount = 0;

        foreach ($packages as $name => $version) {
            $content = $this->registry->get($name);

            if ($content === null) {
                continue;
            }

            $lines[] = '---';
            $lines[] = '';
            $lines[] = $content;
            $lines[] = '';
            $guidelineCount++;
        }

        // Include project-specific instructions
        if ($basePath !== '') {
            $projectMd = $basePath . '/.ai/guidelines/project.md';

            if (file_exists($projectMd)) {
                $projectContent = file_get_contents($projectMd);

                if ($projectContent !== false) {
                    $lines[] = '---';
                    $lines[] = '';
                    $lines[] = '## Project-Specific Instructions';
                    $lines[] = '';
                    $lines[] = $projectContent;
                    $lines[] = '';
                }
            }
        }

        return implode("\n", $lines);
    }

    /**
     * Generate .mcp.json configuration for AI agent auto-discovery.
     */
    public function generateMcpJson(string $basePath): string
    {
        $config = [
            'mcpServers' => [
                'lattice-catalyst' => [
                    'command' => 'php',
                    'args' => ['lattice', 'catalyst:mcp'],
                    'cwd' => $basePath,
                ],
            ],
        ];

        return (string) json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    /**
     * @return array<string, string>
     */
    public function getDetectedPackages(): array
    {
        return $this->detectedPackages;
    }
}
